name: Docker build and push template
on:
  push:
    branches:
      - main
      - develop
jobs:
  build-application:
    runs-on: ubuntu-latest
    services:
      webserver:
        image: devpanel/php:8.3-base
        env:
          DP_APP_ID: 'drupal-11'
          APP_ROOT: '/var/www/html'
          WEB_ROOT: '/var/www/html/web'
          CODES_USER_DATA_DIR: '/var/www/html/.vscode'
          CODES_WORKING_DIR: '/var/www/html'
          APACHE_RUN_USER: 'www'
          APACHE_RUN_GROUP: 'www'
          CODES_ENABLE: 'yes'
          DB_HOST: mysql
          DB_PORT: 3306
          DB_ROOT_PASSWORD: root
          DB_NAME: drupaldb
          DB_USER: user
          DB_PASSWORD: password
          DB_DRIVER: mysql
        ports:
          - 80:80
        volumes:
          - ${{ github.workspace }}:/app/  # Mounting the checked-out code
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: drupaldb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Set up Docker Environment
      uses: docker/setup-buildx-action@v3

    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Drupal
      run: |
        echo "PREPARE DIR FOR INSTALL"
        docker exec ${{ job.services.webserver.id }} bash -c "sudo rm -rf \$APP_ROOT && sudo mkdir -p \$APP_ROOT"
        docker exec ${{ job.services.webserver.id }} bash -c "sudo cp -r /app/. \$APP_ROOT/." 
        docker exec ${{ job.services.webserver.id }} bash -c "sudo chown -R www:www \$APP_ROOT && chmod +x \$APP_ROOT/.devpanel/init-container.sh"
        docker exec ${{ job.services.webserver.id }} bash -c "export && cd \$APP_ROOT && ls -al"
        echo "INSTALL CUSTOM PACKAGE"
        docker exec ${{ job.services.webserver.id }} bash -c "cd \$APP_ROOT && bash .devpanel/custom_package_installer.sh"
        echo "INSTALL DRUPAL"
        docker exec ${{ job.services.webserver.id }} bash -c "cd \$APP_ROOT && bash .devpanel/init.sh"
        docker exec ${{ job.services.webserver.id }} bash -c "cd \$APP_ROOT && ls -al"
        # echo "DUMPS DATABASE + STATIC FILE" 
        # docker exec ${{ job.services.webserver.id }} bash -c "cd \$APP_ROOT && bash .devpanel/quickstart/create_quickstart.sh" 

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set env to testing environment
      run: |
        echo "IMAGE_TAG=ghcr.io/devpanel-developer/demo-scalability:latest" >> $GITHUB_ENV

    - name: Commit and push the container state to Docker Hub
      run: |
        docker commit ${{ job.services.webserver.id }} ${{ env.IMAGE_TAG }}
        docker push ${{ env.IMAGE_TAG }}
